In [66]:
import pandas as pd

In [67]:
dir='result/testcif/AEL/AEL_0_0.csv'
df= pd.read_csv(dir,index_col=0)
df

    neighbor_num  isite atom         x             y         z  front_index
0              0      0  Si1  0.000000  0.000000e+00  0.000000          NaN
1              1     48   O1  0.000000  0.000000e+00  1.608831          0.0
2              1     60   O1  1.517437  2.081668e-17 -0.538568          0.0
3              1     40   O1 -0.765072 -1.308646e+00 -0.542148          0.0
4              1     92   O1 -0.756643  1.317836e+00 -0.532389          0.0
5              2      6  Si1 -0.292498 -7.191173e-01  3.017964          1.0
6              2      1  Si1  2.794983 -8.535076e-01 -1.020307          2.0
7              2     32  Si1 -2.151182 -1.650862e+00 -1.286643          3.0
8              2     29  Si1 -1.163457  2.209846e+00 -1.810475          4.0
9              3     58   O1  1.028638 -6.491240e-01  3.935753          5.0
10             3     63   O1 -1.503769  3.360361e-02  3.765563          5.0
11             3     46   O1 -0.686483 -2.260058e+00  2.768780          5.0
12             3     93   O1  3.611457 -1.605622e-02 -2.126961          6.0
13             3     49   O1  3.752663 -1.145955e+00  0.238924          6.0
14             3     41   O1  2.303105 -2.245579e+00 -1.662184          6.0
15             3     74   O1 -3.381865 -1.186781e+00 -0.358331          7.0
16             3     97   O1 -2.211251 -8.647387e-01 -2.691309          7.0
17             3    108   O1 -2.248168 -3.234492e+00 -1.553988          7.0
18             3     45   O1 -0.902899  1.364784e+00 -3.156086          8.0
19             3    105   O1 -0.276911  3.552366e+00 -1.831358          8.0
20             3     72   O1 -2.723254  2.597897e+00 -1.720123          8.0
21             4     15  Si1  1.678745 -9.429895e-01  5.379944          9.0
22             4      7  Si1 -3.087481  1.343903e-01  4.038271         10.0
23             4     10  Si1 -0.028884 -3.708914e+00  3.015894         11.0
24             4     28  Si1  3.551388  7.700674e-01 -3.531626         12.0
25             4      7  Si1  4.417844 -2.157521e+00  1.298456         13.0
26             4     33  Si1  2.563663 -3.090641e+00 -3.007795         14.0
27             4     33  Si1 -4.941662 -7.987298e-01 -0.267980         15.0
28             4      5  Si1 -1.394777 -2.728734e-02 -3.797963         16.0
29             4     39  Si1 -2.047111 -4.823577e+00 -1.396226         17.0
30             4      5  Si1 -1.394777 -2.728734e-02 -3.797963         18.0
31             4     36  Si1  0.547259  4.828376e+00 -2.363379         19.0
32             4     28  Si1 -3.953937  3.061978e+00 -0.791812         20.0

In [68]:
l1=df[['x','y','z']].drop_duplicates().sort_values(by=['x','y','z'])

In [69]:
l2=df.sort_values(by=['x','y','z'])

In [70]:
l1.index.sort_values(),l2.index.sort_values()

(Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
             17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
            dtype='int64'),
 Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
             17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
            dtype='int64'))

In [71]:
df[df.isite==5].loc[:,'x':'z'].round({key:6 for key in ['x','y','z']}).drop_duplicates()

           x         y         z
28 -1.394777 -0.027287 -3.797963

In [72]:
l3=df.loc[:,'x':'z'].round(6).drop_duplicates()
l3.index.size,df.index.size

(32, 33)

In [73]:
df2=pd.read_csv('result/allzeorite/SBN/SBN_0_0.csv',index_col=0)

In [74]:
from read_info import read_nood
nood=read_nood(df2)
nood

[([-5.551115123125783e-17, 0.0],
  [0.0, 1.1102230246251563e-16],
  [0.0, 1.6094281312198953]),
 ([0.0, 1.5177025387611127], [0.0, 0.0], [-0.5490936519629567, 0.0]),
 ([-0.7778825603470509, 0.0],
  [0.0, 1.301097630734365],
  [-0.5406501522863929, 0.0]),
 ([-0.7190320146447315, 0.0],
  [-1.337268443456669, 0.0],
  [-0.5490936529941972, 0.0]),
 ([-0.4767786672145901, -5.551115123125783e-17],
  [1.1102230246251563e-16, 0.7967666296816263],
  [1.6094281312198953, 2.924790842314613]),
 ([1.5177025387611127, 2.3398819975639547],
  [-1.0369518725027551, 0.0],
  [-1.4740528509992032, -0.5490936519629567]),
 ([-1.5740024891777988, -0.7778825603470509],
  [1.301097630734365, 2.6319990772437825],
  [-0.5406501522863929, -0.107951157578467]),
 ([-0.7190320146447315, -0.1953654216785645],
  [-2.552098451963911, -1.337268443456669],
  [-1.4736941994806267, -0.5490936529941972]),
 ([-0.4767786672145901, -0.0018608935290227],
  [0.0024122867069622, 0.7967666296816263],
  [2.924790842314613, 4.237470215402661]),
 ([-2.082009393970158, -0.4767786672145901],
  [0.7967666296816263, 0.921458729428187],
  [2.920295083994448, 2.924790842314613]),
 ([-0.4767786672145901, 0.1726614945660134],
  [0.7967666296816263, 2.270043376906982],
  [2.920653734268178, 2.924790842314613]),
 ([2.3398819975639547, 2.8347524649153883],
  [-1.0369518725027551, -0.2995435779326731],
  [-2.8162864883383127, -1.4740528509992032]),
 ([2.3398819975639547, 3.6126350252624393],
  [-1.600641208667038, -1.0369518725027551],
  [-1.4740528509992032, -0.6662082048320246]),
 ([1.3458460517690083, 2.3398819975639547],
  [-2.2517818810099977, -1.0369518725027551],
  [-1.849559745522676, -1.4740528509992032]),
 ([-2.0489202628633665, -1.5740024891777988],
  [2.6319990772437825, 3.4263534202184465],
  [-1.4206305306665157, -0.107951157578467]),
 ([-1.5740024891777988, -0.6052210657810375],
  [2.6319990772437825, 3.5711410076413466],
  [-0.107951157578467, 0.7705754507618898]),
 ([-2.859891954317209, -1.5740024891777988],
  [2.2225563601625518, 2.6319990772437825],
  [-0.107951157578467, 0.7702168004881598]),
 ([-0.1953654216785645, 1.3458460517690083],
  [-2.552098451963911, -2.2517818810099977],
  [-1.849559745522676, -1.4736941994806267]),
 ([-0.3012946088564727, -0.1953654216785645],
  [-3.940055561901177, -2.552098451963911],
  [-1.4736941994806267, -0.6658495516082663]),
 ([-1.0791771692035237, -0.1953654216785645],
  [-2.6389579311668125, -2.552098451963911],
  [-2.8159278351145547, -1.4736941994806267]),
 ([-0.0018608935290227, 0.4730568801565449],
  [-0.7919420562677015, 0.0024122867069622],
  [4.237470215402661, 5.550149588490711]),
 ([-3.3547624216686427, -2.082009393970158],
  [0.921458729428187, 1.4851480655924696],
  [2.112450437827269, 2.920295083994448]),
 ([0.1726614945660134, 0.2785906817439219],
  [2.270043376906982, 3.658000486844248],
  [2.112809086395818, 2.920653734268178]),
 ([2.8347524649153883, 4.120641930054799],
  [-0.2995435779326731, 0.1098991391485577],
  [-3.694454446404939, -2.8162864883383127]),
 ([3.6126350252624393, 5.217865752018007],
  [-1.7253333084135984, -1.600641208667038],
  [-0.6662082048320246, -0.6617124465118593]),
 ([-0.1953654216785645, 1.3458460517690083],
  [-2.552098451963911, -2.2517818810099977],
  [-1.849559745522676, -1.4736941994806267]),
 ([-2.523838036548934, -2.0489202628633665],
  [3.4263534202184465, 4.220707763193111],
  [-2.7333099037545647, -1.4206305306665157]),
 ([-0.6052210657810375, 0.2785906817439219],
  [3.5711410076413466, 3.658000486844248],
  [0.7705754507618898, 2.112809086395818]),
 ([-3.3547624216686427, -2.859891954317209],
  [1.4851480655924696, 2.2225563601625518],
  [0.7702168004881598, 2.112450437827269]),
 ([1.3458460517690083, 2.3398819975639547],
  [-2.2517818810099977, -1.0369518725027551],
  [-1.849559745522676, -1.4740528509992032]),
 ([-0.9507347706370765, -0.3012946088564727],
  [-5.413332309126533, -3.940055561901177],
  [-0.6658495516082663, -0.6617124435618311]),
 ([-2.047958592600285, -1.0791771692035237],
  [-3.578099861564376, -2.6389579311668125],
  [-3.694454443454912, -2.8159278351145547])]

In [75]:
nooddf=pd.DataFrame(nood)
nooddf.head(5)

,0,1,2
0,"[-5.551115123125783e-17, 0.0]","[0.0, 1.1102230246251563e-16]","[0.0, 1.6094281312198953]"
1,"[0.0, 1.5177025387611127]","[0.0, 0.0]","[-0.5490936519629567, 0.0]"
2,"[-0.7778825603470509, 0.0]","[0.0, 1.301097630734365]","[-0.5406501522863929, 0.0]"
3,"[-0.7190320146447315, 0.0]","[-1.337268443456669, 0.0]","[-0.5490936529941972, 0.0]"
4,"[-0.4767786672145901, -5.551115123125783e-17]","[1.1102230246251563e-16, 0.7967666296816263]","[1.6094281312198953, 2.924790842314613]"

In [76]:
df3=pd.read_csv('result/allzeorite/SBN/SBN_0_0.csv',index_col=0).round({key:6 for key in ['x','y','z']})
nood=read_nood(df3)

In [77]:
nooddf=pd.DataFrame(nood).astype(str)
nooddf.drop_duplicates().index.size

30

In [78]:
nooddf.index.size

32

In [79]:
df=pd.read_csv('result/allzeorite/NAB/NAB_0_0.csv',index_col=0).round(6)
nooddf=pd.DataFrame(read_nood(df)).astype(str)

In [80]:
disite=df.index.size-df.loc[:,'x':'z'].round(6).drop_duplicates().index.size
disite

6

In [81]:
dnood=nooddf.index.size-nooddf.drop_duplicates().index.size
dnood

4

In [82]:
df[df.isite==24].round(6)

    neighbor_num  isite atom         x    y        z  front_index
17             3     24   O1 -2.582797  0.0 -1.84576          7.0
20             3     24   O1 -2.582797  0.0 -1.84576          8.0

In [83]:
nooddf

                         0                       1                       2
0               [0.0, 0.0]              [0.0, 0.0]         [0.0, 1.611458]
1          [0.0, 1.524595]              [0.0, 0.0]        [-0.521927, 0.0]
2         [-0.762297, 0.0]         [-1.31108, 0.0]        [-0.544765, 0.0]
3         [-0.762297, 0.0]          [0.0, 1.31108]        [-0.544765, 0.0]
4          [0.0, 1.204451]              [0.0, 0.0]    [1.611458, 2.685003]
5     [1.524595, 2.930376]              [0.0, 0.0]   [-0.521927, 0.269894]
6   [-2.067413, -0.762297]   [-1.484214, -1.31108]  [-1.477449, -0.544765]
7   [-2.067413, -0.762297]     [1.31108, 1.484214]  [-1.477449, -0.544765]
8     [1.128366, 1.204451]        [-1.319701, 0.0]    [2.685003, 3.599271]
9     [1.204451, 2.582797]              [0.0, 0.0]     [1.84576, 2.685003]
10    [1.128366, 1.204451]         [0.0, 1.319701]    [2.685003, 3.599271]
11    [2.930376, 3.770718]         [0.0, 1.319701]   [-0.098208, 0.269894]
12    [2.582797, 2.930376]              [0.0, 0.0]     [0.269894, 1.84576]
13    [2.930376, 3.770718]        [-1.319701, 0.0]   [-0.098208, 0.269894]
14  [-3.216852, -2.067413]  [-2.272299, -1.484214]  [-1.477449, -0.676825]
15  [-2.067413, -1.682232]  [-2.272299, -1.484214]  [-2.824238, -1.477449]
16  [-2.582797, -2.067413]        [-1.484214, 0.0]   [-1.84576, -1.477449]
17  [-2.067413, -1.682232]    [1.484214, 2.272299]  [-2.824238, -1.477449]
18  [-3.216852, -2.067413]    [1.484214, 2.272299]  [-1.477449, -0.676825]
19  [-2.582797, -2.067413]         [0.0, 1.484214]   [-1.84576, -1.477449]
20    [0.743184, 1.128366]  [-2.107786, -1.319701]     [3.599271, 4.94606]
21    [2.582797, 2.930376]              [0.0, 0.0]     [0.269894, 1.84576]
22    [0.743184, 1.128366]    [1.319701, 2.107786]     [3.599271, 4.94606]
23    [3.770718, 4.920156]    [1.319701, 2.107786]  [-0.898831, -0.098208]
24    [1.204451, 2.582797]              [0.0, 0.0]     [1.84576, 2.685003]
25    [3.770718, 4.920156]  [-2.107786, -1.319701]  [-0.898831, -0.098208]
26  [-4.057194, -3.216852]     [-3.592, -2.272299]  [-0.676825, -0.308723]
27  [-1.682232, -1.606147]     [-3.592, -2.272299]  [-3.738506, -2.824238]
28  [-2.582797, -2.067413]         [0.0, 1.484214]   [-1.84576, -1.477449]
29  [-1.682232, -1.606147]       [2.272299, 3.592]  [-3.738506, -2.824238]
30  [-4.057194, -3.216852]       [2.272299, 3.592]  [-0.676825, -0.308723]
31  [-2.582797, -2.067413]        [-1.484214, 0.0]   [-1.84576, -1.477449]